baseurl = "https://paulcampbell.netlify.com/"
languageCode = "en-us"
title = "Paul Campbell"
theme = "tuftesque"
googleAnalytics = "UA-128595985-1"
disqusShortname = "paulsblog-2"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1
    [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 3
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "CV"
    url = "/docs/paul_campbell_cv_2018.pdf"
    weight = 4
[[menu.main]]
    name = "<i class='fa fa-list-alt fa-lg' title='categories'></i>"
    url = "/categories/"
    weight = 5

[params]
    showtitle = false
    showPoweredBy = false
    
    author = "Paul Campbell"
    
    description = "A website built through Hugo and blogdown."
    
    backgroundcolor = "#f5f5f5"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "obsidian"

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

