---
title: D3 Sankey Diagrams from tidy data frames in R
author: Paul Campbell
date: '2018-03-01'
slug: sankey
categories:
  - R
  - Visualisation
tags:
  - D3
  - purrr
  - tidygraph
  - htmlwidgets
draft: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



Get the data in the format we want

```{r message=FALSE, warning=FALSE}

library(tidyverse)
library(tidygraph)
library(igraph)
library(networkD3)

# https://www.kaggle.com/unitednations/refugee-data/data
asylum_seekers_raw <- read_csv("../../data/asylum_seekers.csv") %>% 
  rename(Destination = `Country / territory of asylum/residence`)

# get the top 10 countries of origin by 'Total decisions'
top_orig <- asylum_seekers_raw %>%
  filter(Year == 2016) %>%  
  group_by(Origin) %>% 
  summarise(total = sum(`Total decisions`, na.rm = TRUE)) %>% 
  top_n(10, total) %>% 
  dplyr::pull(1)

# get the top 10 countries of origin by 'Total decisions'
top_dest <- asylum_seekers_raw %>%
  filter(Year == 2016) %>%  
  group_by(Destination) %>% 
  summarise(total = sum(`Total decisions`, na.rm = TRUE)) %>% 
  top_n(10, total) %>% 
  dplyr::pull(1)

# list of destination countries we want to look at
euro_countries <- 
  c("Germany", "Sweden", "France", "United Kingdom", 
    "Netherlands", "Switzerland", "Italy", "Belgium")

# filter and clean the data we want to visualise
asylum_seekers <- asylum_seekers_raw %>% 
  filter(Origin %in% top_orig, 
         Destination %in% top_dest) %>%
  select(1, 3, 2, 8, 10) %>% 
  filter(Year == 2016) %>% 
  select(-Year) %>% 
  drop_na() %>% 
  gather(Decision, Weight, 3:4)

head(asylum_seekers)
```

```{r}
################################# SANKEY FUNCTION ######################################
sankey_from_data_frame <- function(data, val_col, ...) {
  
  weight <- enquo(val_col)
  
  df <- 1:(ncol(data)-2) %>% 
    # collapse dataframe into 3 columns: from, to, weight
    map_df(~ select(data, 
                    from = !! quo(names(data)[.x]), 
                    to = !! quo(names(data)[.x + 1]), 
                    !! weight)) %>% 
    drop_na() %>% 
    group_by(from, to) %>% 
    summarise(weight = sum(!! weight)) %>% 
    mutate(colour = to) # used to colour edges in the sankeyNetwork function
  
  # create igraph from data frame then convert to tidygraph
  ig <- #igraph::graph_from_data_frame(df) %>% 
    tidygraph::as_tbl_graph(df)
  
  # extract node data and reduce ids by 1 (required for D3 plotting)
  nodes <- as_tibble(ig) %>% 
    rowid_to_column("id") %>% 
    mutate(id = id -1) %>% 
    as.data.frame
  
  # do the same for the edges
  edges <- ig %>% 
    activate(edges) %>% 
    as_tibble() %>% 
    mutate(from = from - 1, to = to - 1) %>% 
    as.data.frame
  
  # plot work networkD3::sankeyNetwork
  sankeyNetwork(Links = edges, Nodes = nodes, Source = "from", Target = "to", 
                NodeID = "name", Value = "weight", #LinkGroup = "colour", 
                fontSize = 14, fontFamily = "Oswald", width = "90%")
}
################################ END OF FUNCTION ##################################
```

Run the function on our data: 

```{r eval=FALSE}
sankey_from_data_frame(data = asylum_seekers, val_col = Weight)
```

### Asylum Seeker flows in 2016 from top 10 origin countries to top 10 destination countries 

```{r echo=FALSE}

sankey_from_data_frame(data = asylum_seekers, val_col = Weight)

```